import LegalPage from "@/components/legal-page";

export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" intro="This policy explains what Sago collects through sago.world, why it is used and the choices available to you." sections={[
    { title: "Who is responsible", children: <><p>This website is operated under the Sago brand. The responsible legal entity and registered address have not been supplied for this site and must be added before launch. Until then, contact <a href="mailto:hello@sago.world">hello@sago.world</a> with privacy questions.</p></> },
    { title: "Information we collect", children: <><p>The site is designed to collect as little information as possible. The retailer search and filters stay in your browser and are not submitted to us. The age gate stores a local browser flag so you do not have to repeat it on every visit.</p><p>If you complete the newsletter form, we would receive the email address and consent record only if a delivery service is connected. Newsletter delivery is not currently active, so the form does not send or store your details.</p><p>Optional privacy-friendly analytics loads only after you choose “Allow analytics”. It may process information such as pages visited, device and browser information, approximate location and referral information. Review Vercel’s current privacy documentation before launch and confirm the configured retention and international-transfer terms.</p></> },
    { title: "How we use information", children: <><p>We use information to operate the site, remember age verification, respond to messages, provide an opted-in newsletter if activated, measure site performance after consent, and meet legal or security obligations.</p><p>We do not sell personal information. We do not use advertising pixels, session replay, embedded media or targeted advertising on the current site.</p></> },
    { title: "Your choices and rights", children: <><p>You can reject analytics in the consent banner, clear the site’s local storage, and contact us to ask about access, correction, deletion, objection or other rights that apply where you live. Rights and response periods depend on your jurisdiction.</p><p>We retain information only for as long as needed for the purpose collected, legal obligations, dispute resolution and security. Exact retention periods should be confirmed before launch.</p></> },
    { title: "International processing and children", children: <><p>Service providers may process information in countries other than yours. Any required transfer safeguards must be confirmed with the providers and the responsible legal entity.</p><p>This is an alcohol website and is not directed to children. Do not submit information if you are below the legal drinking age where you live.</p></> },
  ]} />;
}
